/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/iVThwiFFC1i
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Carousel, CarouselContent, CarouselItem, CarouselPrevious, CarouselNext } from "@/components/ui/carousel"
import { Button } from "@/components/ui/button"

export function Hero() {
  return (
    (<section className="w-full py-12 md:py-24 lg:py-32">
      <div className="container grid grid-cols-1 lg:grid-cols-2 gap-8 items-center">
        <Carousel className="rounded-lg overflow-hidden">
          <CarouselContent>
            <CarouselItem>
              <img
                src="/placeholder.svg"
                width={800}
                height={450}
                alt="Hero Image 1"
                className="aspect-video object-cover" />
            </CarouselItem>
            <CarouselItem>
              <img
                src="/placeholder.svg"
                width={800}
                height={450}
                alt="Hero Image 2"
                className="aspect-video object-cover" />
            </CarouselItem>
            <CarouselItem>
              <img
                src="/placeholder.svg"
                width={800}
                height={450}
                alt="Hero Image 3"
                className="aspect-video object-cover" />
            </CarouselItem>
          </CarouselContent>
          <CarouselPrevious
            className="absolute top-1/2 left-4 -translate-y-1/2 z-10 text-white hover:text-primary focus:outline-none">
            <ChevronLeftIcon className="h-6 w-6" />
          </CarouselPrevious>
          <CarouselNext
            className="absolute top-1/2 right-4 -translate-y-1/2 z-10 text-white hover:text-primary focus:outline-none">
            <ChevronRightIcon className="h-6 w-6" />
          </CarouselNext>
        </Carousel>
        <div className="space-y-4">
          <div className="flex items-center justify-between">
            <h1 className="text-4xl font-bold tracking-tighter sm:text-5xl md:text-6xl">
              Unlock Your Business Potential
            </h1>
            <div className="flex gap-2">
              <Button>Get Started</Button>
              <Button variant="secondary">Learn More</Button>
            </div>
          </div>
          <p className="text-muted-foreground md:text-xl">
            Our platform provides the tools and insights you need to drive growth and success. Discover how we can help
            your business thrive.
          </p>
        </div>
      </div>
    </section>)
  );
}

function ChevronLeftIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m15 18-6-6 6-6" />
    </svg>)
  );
}


function ChevronRightIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m9 18 6-6-6-6" />
    </svg>)
  );
}
